# Generated by Django 5.0.9 on 2024-11-24 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
