# Generated by Django 5.0.9 on 2024-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_inventory_date_added_alter_product_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.CharField(default='2024-11-24 17:07:02', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_added',
            field=models.CharField(default='2024-11-24 17:07:02', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.CharField(default='2024-11-24 17:07:02', max_length=100),
        ),
    ]
