# Generated by Django 5.0.9 on 2024-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_cart_date_added_remove_cart_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.CharField(default='2024-11-24 17:22:54', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_added',
            field=models.CharField(default='2024-11-24 17:22:54', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.CharField(default='2024-11-24 17:22:54', max_length=100),
        ),
    ]
