# Generated by Django 4.2.9 on 2024-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_user_id_cart_user_alter_cart_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.CharField(default='2024-12-26 17:59:49', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_added',
            field=models.CharField(default='2024-12-26 17:59:49', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.CharField(default='2024-12-26 17:59:49', max_length=100),
        ),
    ]
